export type Coverage={start:string;end:string};
export type Health={health:string;status:string;project_phase:string;development_data_available:boolean;development_coverage:Coverage;real_money_authorized:boolean};
export type FamilyBudget={family_id:string;experiments_consumed:number;experiments_limit:number;trials_consumed:number;trials_limit:number};
export type Research={champion:string;experiments_completed:number;evidence:string;backtest_substrate:string;engine_version:string;execution_model_version:string;cost_model_version:string;synthetic_validation:string;search_memory?:{version:string;status:string;families_tracked:number}|null;adaptive_search?:{material_economic_hypotheses:number;configuration_variants:number;profile_trials:number;adaptive_decisions:number;result_dependent_forks:number;supervised_model_fits?:number}|null;selected_family?:{name:string;terminal_classification:string}|null;wp005_integrity?:{status:string;source_provenance_classification:string;independent_reconciliation:string;integrity_replay_profiles:number;matched_control_classification:string}|null;remote_ci?:{policy:string;work_packages:Record<string,{status:string;head:string;run_id:number;evidence:string}>}|null;latest_family?:{name:string;root_family:string;primary_experiment_id:string;novelty_classification:string;terminal_classification:string}|null;order_flow_substrate?:{version:string;status:string;content_hash:string;eligible_1h_buckets:number;eligible_4h_buckets:number;oracle_reconciliation:string}|null;artifact_storage?:{version:string;status:string;trial_artifact_format:string;historical_evidence_rewritten:boolean}|null;supervised_challenger?:{version:string;status:string;primary:string;secondary:string;model_fits:number;terminal_classification:string;leakage_audit:string;model_reconciliation:string}|null;exogenous_foundation?:{contract_version:string;status:string;gdelt:{version:string;status:string;hourly_rows:number};alfred:{version:string;status:string;series:number};combined_context:{version:string;status:string;rows:number};asof_reconciliation:string;adaptive_design:string}|null;sealed_evaluation?:{version:string;status:string;dataset_state:string;authorized_btc_queries:number;consumed_btc_queries:number;isolation:string;seal_eligible_candidates:number;candidates_assessed:number}|null;family_budgets?:FamilyBudget[]};
export type ExperimentSummary={experiment_id:string;classification:string;primary_metric:string;primary_result:number|null;trade_count:number|null;validation_status:string;evidence_window?:string};
export type ExperimentPayload={evidence_stage:string;latest_checkpoint:string;next_checkpoint:string;experiments:ExperimentSummary[]};
export type Candle={open_time:string;open:number;high:number;low:number;close:number;complete?:boolean};
export type CandlePayload={classification:string;coverage:Coverage;candles:Candle[]};
export async function request<T>(url:string):Promise<T>{const response=await fetch(url);if(!response.ok)throw new Error(`API ${response.status}`);return response.json() as Promise<T>}
export type AnalysisPlan={direction:string;entry_rule:string;entry_semantics:string;execution_model:string;exit_policy:string;reference_price:number;stop_price:number;target_price:number;stop_fraction:number;target_fraction:number;max_hold_minutes:number;expiry_time:string;leverage:boolean;short:boolean;order_placed:boolean};
export type Analysis={analysis_version:string;classification:string;symbol:string;strategy_version:string;variant:string;feature_version:string;prospective_features_version?:string;analysis_id?:string;research_status:string;champion_status:string;analysis_time:string;signal_time:string|null;data_status:string;data_detail:string;decision:'NO_TRADE'|'LONG';plan:AnalysisPlan|null;reference_price?:number;paper_trade_persisted:boolean;real_money:boolean;paper_trades_completed?:number;real_money_authorized?:boolean};
export async function analyseMarket():Promise<Analysis>{const response=await fetch('/api/v1/product/analysis',{method:'POST'});if(!response.ok)throw new Error(`API ${response.status}`);return response.json() as Promise<Analysis>}
export type PaperTrade={trade_id:string;evidence_version:string;evidence_stage:string;analysis_id:string;strategy_version:string;variant:string;research_status:string;champion_status:string;symbol:string;direction:string;status:'PENDING_ENTRY'|'OPEN'|'CLOSED_TARGET'|'CLOSED_STOP'|'CLOSED_EXPIRY'|'INVALIDATED';created_at:string;signal_time:string;entry_execution:string;entry_minute:string;ambiguous_fill_policy:string;execution_model_version:string;reference_price:number;stop_price:number;target_price:number;max_hold_minutes:number;expiry_time:string;entry_time:string|null;entry_price:number|null;exit_time:string|null;exit_price:number|null;exit_reason:string|null;net_r:number|null;holding_minutes:number|null;resolution_detail:string;last_update_time:string;real_money:boolean};
export type PaperListing={evidence_version:string;evidence_stage:string;contract:string;research_status:string;champion_status:string;strategy_version:string;max_hold_minutes:number;statuses:string[];active:PaperTrade[];recent:PaperTrade[];recorded:number;real_money:boolean};
export type PaperLifecycle={evidence_version:string;updated:number;trades:PaperTrade[];errors:{trade_id:string;error:string}[];real_money:boolean};
async function send<T>(url:string):Promise<T>{const response=await fetch(url,{method:'POST'});const body=await response.json().catch(()=>null);if(!response.ok)throw new Error(body?.detail??`API ${response.status}`);return body as T}
export function createPaperTrade(){return send<{analysis_id:string;trade:PaperTrade;real_money:boolean}>('/api/v1/product/paper-trades')}
export function advancePaperTrades(){return send<PaperLifecycle>('/api/v1/product/paper-trades/lifecycle')}
export function readPaperTrades(){return request<PaperListing>('/api/v1/product/paper-trades')}
export type LiveCandle={open_time:string;open:number;high:number;low:number;close:number};
export type LiveMarket={classification:string;symbol:string;interval:string;status:string;detail:string;candles:LiveCandle[]};
export type PaperStatistics={statistics_version:string;evidence_version:string;evidence_stage:string;label:string;development_backtest_metrics_included:boolean;total_paper_trades:number;pending_entry:number;open:number;active:number;closed:number;invalidated:number;closed_target:number;closed_stop:number;expiries:number;realized_trades:number;wins:number;losses:number;breakeven:number;win_rate:number|null;mean_realized_r:number|null;cumulative_realized_r:number|null;expectancy_r_per_trade:number|null;max_drawdown_r:number|null;best_realized_r:number|null;worst_realized_r:number|null;empty:boolean;empty_detail:string|null;champion_status:string;real_money:boolean};
export function readLiveMarket(){return request<LiveMarket>('/api/v1/product/market/recent')}
export function readPaperStatistics(){return request<PaperStatistics>('/api/v1/product/paper-trades/statistics')}
