import { useEffect, useState } from 'react';
import { ExperimentPayload, Health, Research, request } from './api';
import { Market } from './Market';

const pages = ['Dashboard', 'Market', 'Paper Trades', 'Statistics', 'Research Lab', 'System'] as const;
type Page = typeof pages[number];

export function App() {
  const [health, setHealth] = useState<Health | null>();
  const [research, setResearch] = useState<Research | null>(null);
  const [experiments, setExperiments] = useState<ExperimentPayload | null>(null);
  const [page, setPage] = useState<Page>('Dashboard');
  useEffect(() => {
    request<Health>('/api/v1/system/health').then(setHealth).catch(() => setHealth(null));
    request<Research>('/api/v1/research/status').then(setResearch).catch(() => setResearch(null));
    request<ExperimentPayload>('/api/v1/research/experiments').then(setExperiments).catch(() => setExperiments(null));
  }, []);
  return <><header><b>TRADING BOT</b><span>PAPER ONLY</span></header><nav>{pages.map(item => <button key={item} onClick={() => setPage(item)}>{item}</button>)}</nav><main><h1>{page}</h1>
    {page === 'Dashboard' && <><div className="card">Backend: {health === undefined ? 'checking' : health?.health ?? 'unavailable'} · {health?.status ?? 'unknown'}</div><button disabled>ANALYZE MARKET</button><h2>No approved strategy</h2><p>No market analysis available yet.</p></>}
    {page === 'Market' && <Market available={health?.development_data_available === true} />}
    {page === 'Paper Trades' && <div className="card">No paper trades exist.</div>}
    {page === 'Statistics' && <div className="card">No approved strategy performance statistics exist.</div>}
    {page === 'Research Lab' && <><div className="card">Champion: {research?.champion ?? 'NONE'}<br />Experiments completed: {research?.experiments_completed ?? 0}<br />Evidence stage: {experiments?.evidence_stage ?? 'NONE'}<br />Backtest substrate: {research?.backtest_substrate ?? 'unavailable'}<br />Models: {research?.engine_version ?? 'unavailable'} / {research?.execution_model_version ?? 'unavailable'} / {research?.cost_model_version ?? 'unavailable'}<br />Synthetic validation: {research?.synthetic_validation ?? 'unavailable'} — infrastructure check only, not trading evidence.</div><p className="banner">DEVELOPMENT RESEARCH — NOT APPROVED STRATEGY PERFORMANCE</p>
      <section className="card" aria-label="Scientific search memory"><h2>Scientific search memory</h2>Memory: {research?.search_memory?.version ?? 'unavailable'} / {research?.search_memory?.status ?? 'unavailable'}<br />Root families: {research?.search_memory?.families_tracked ?? 'unavailable'}<br />Cumulative hypotheses: {research?.adaptive_search?.material_economic_hypotheses ?? 'unavailable'} · Configurations: {research?.adaptive_search?.configuration_variants ?? 'unavailable'} · Profile/seed trials: {research?.adaptive_search?.profile_trials ?? 'unavailable'}<br />Adaptive decisions: {research?.adaptive_search?.adaptive_decisions ?? 'unavailable'} · Result-dependent forks: {research?.adaptive_search?.result_dependent_forks ?? 'unavailable'}<br />Selected family: {research?.selected_family?.name ?? 'unavailable'} · {research?.selected_family?.terminal_classification ?? 'unavailable'}<p>No strategy approval follows from a positive development result. Consumed budgets are not reset by renaming.</p>{research?.family_budgets?.map(item => <p key={item.family_id}>{item.family_id}: {item.experiments_consumed}/{item.experiments_limit} configurations · {item.trials_consumed}/{item.trials_limit} trials</p>)}</section>
      <section className="card" aria-label="WP-005 integrity"><h2>WP-005 integrity</h2>Status: {research?.wp005_integrity?.status ?? 'unavailable'}<br />Source provenance: {research?.wp005_integrity?.source_provenance_classification ?? 'unavailable'}<br />Independent reconciliation: {research?.wp005_integrity?.independent_reconciliation ?? 'unavailable'}<br />Search memory: {research?.search_memory?.version ?? 'unavailable'}<br />Matched controls: {research?.wp005_integrity?.matched_control_classification ?? 'unavailable'}<p>Underlying ALIGNED evidence remains INCONCLUSIVE. Champion NONE.</p></section>
      <section className="card" aria-label="New algorithm family"><h2>New algorithm family</h2>Family: {research?.latest_family?.name ?? 'unavailable'}<br />Root: {research?.latest_family?.root_family ?? 'unavailable'}<br />Novelty gate: {research?.latest_family?.novelty_classification ?? 'unavailable'}<br />Primary variant: {research?.latest_family?.primary_experiment_id ?? 'unavailable'}<br />Development classification: {research?.latest_family?.terminal_classification ?? 'unavailable'}<p>Admitted before any market result. FAM-BREAKOUT remains exhausted and no prior budget was reset. Champion NONE.</p></section>
      <section className="card" aria-label="Sealed evaluation"><h2>Sealed evaluation</h2>System: {research?.sealed_evaluation?.version ?? 'unavailable'} — {research?.sealed_evaluation?.status === 'LOCKED_NO_AUTHORIZED_QUERY' ? 'LOCKED — NO AUTHORIZED QUERY' : research?.sealed_evaluation?.status ?? 'unavailable'}<br />Reserved BTC data: {research?.sealed_evaluation?.dataset_state ?? 'unavailable'}<br />Authorized BTC queries: {research?.sealed_evaluation?.authorized_btc_queries ?? 'unavailable'}<br />Sealed queries consumed: {research?.sealed_evaluation?.consumed_btc_queries ?? 'unavailable'}<br />Seal-eligible candidates: {research?.sealed_evaluation?.seal_eligible_candidates ?? 'unavailable'} of {research?.sealed_evaluation?.candidates_assessed ?? 'unavailable'}<br />Isolation: {research?.sealed_evaluation?.isolation ?? 'unavailable'}<p>No sealed data browser exists. INCONCLUSIVE candidates can never be queried. Champion NONE.</p></section>
      <div className="grid">{experiments?.experiments.map(item => <article className="card" key={item.experiment_id}><b>{item.experiment_id}</b><br />{item.classification}<br />{item.evidence_window}<br />{item.primary_metric}: {item.primary_result ?? 'N/A'}<br />Trades: {item.trade_count ?? 'N/A'} · {item.validation_status}</article>)}</div><p>Latest: {experiments?.latest_checkpoint ?? 'unavailable'} · Next: {experiments?.next_checkpoint ?? 'unavailable'}</p></>}
    {page === 'System' && <div className="card">Backend health: {health?.health ?? 'unavailable'}<br />Project: {health?.project_phase ?? 'unavailable'} / {health?.status ?? 'unavailable'}<br />Development data: {health?.development_data_available ? 'installed' : 'not installed'}<br />Real money authorized: {health?.real_money_authorized ? 'yes' : 'no'}</div>}
  </main></>;
}
