"""Build (or `--check`) the System G1 cycle synthetic diagnostic artifact.

Synthetic method-validation only: no market data is read and no quality threshold is selected.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

from app.g1.cycle_diagnostics import ARTIFACT_PATH, build_diagnostics

DIGITS = 9


def rounded(value: Any) -> Any:
    if isinstance(value, float):
        return round(value, DIGITS)
    if isinstance(value, dict):
        return {key: rounded(item) for key, item in value.items()}
    if isinstance(value, list | tuple):
        return [rounded(item) for item in value]
    return value


def artifact_bytes() -> bytes:
    payload = rounded(build_diagnostics())
    return (json.dumps(payload, indent=2, sort_keys=True, ensure_ascii=True) + "\n").encode()


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    options = parser.parse_args()
    path = ROOT / ARTIFACT_PATH
    content = artifact_bytes()
    if options.check:
        existing = path.read_bytes().replace(b"\r\n", b"\n")
        if existing != content:
            raise SystemExit("cycle synthetic diagnostics do not regenerate byte-identically")
        print("System G1 cycle synthetic diagnostics: PASS (regenerated byte-identically)")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_bytes(content)
    print(f"wrote {ARTIFACT_PATH}")


if __name__ == "__main__":
    main()
