"""Deterministic research simulator infrastructure; contains no market strategy."""

ENGINE_VERSION = "BACKTEST_ENGINE_V2"
EXECUTION_VERSION = "EXECUTION_MODEL_V2"
COST_VERSION = "BTCUSDT_SPOT_COST_V1"
EVENT_SEQUENCE = ("BAR_CLOSE", "SIGNAL_DECISION", "NEXT_1M_OPEN_EXECUTION")
